Completed prep-javascript-variables
nguyenhmary/prep-0422-code-solutions pull request #10
Opened 2022-04-25 17:53 UTC by nguyenhmary

<img width="1024" alt="Screen Shot 2022-04-25 at 10 53 44 AM" src="https://user-images.githubusercontent.com/103335614/165145924-1193885d-0a04-4c69-862f-375efb976287.png">

2022-04-25 23:45 UTC, thebearingedge requested changes

2022-04-25 23:45 UTC, thebearingedge commented on prep-javascript-variables/index.html
> +    var never = 'undefined';
Hi Mary, be sure to leave off the quotes from `undefined` and `null` so that the browser doesn't interpret them as strings.

2022-04-27 01:44 UTC, nguyenhmary commented
![Screen Shot 2022-04-26 at 6 41 52 PM](https://user-images.githubusercontent.com/103335614/165421466-a5668e8e-7702-4f2f-94fc-df51c3c0a8f6.png)

Hi Tim, just updated the code and here's another screen shot of the inspect page!

2022-04-28 17:28 UTC, thebearingedge commented
Hi @nguyenhmary be sure to add, commit, and push the updated code as well.

2022-04-29 05:31 UTC, nguyenhmary commented
Hey Tim! Just added, committed, and pushed the changes!

2022-04-29 14:26 UTC, thebearingedge approved these changes

2022-04-30 03:48 UTC, merged